### ISSUE TITLE
Error-messages

### ISSUE THREAD

**Issue by cfladvad** [genomizer/genomizer-desktop#20]
To make it easier for us to find bugs we could (should?) write more traceable error messages. Also a minor design-fix would be to locate the pop-up message in the middle of the GUI-window instead of in center of screen.

**Comment by rednatto** [comment]
niklasf has some more fancy logging script written that I could steal.
Would be better than syserr atleast.

**Comment by cfladvad** [comment]
I have stolen the class ErrorLogger from server so now its possible to add ErrorLogger.log(string,string) or ErrorLogger.log(string,exception) to all errors we wish to log, whatever that might be? :) Not sure if this work correctly when running through a JAR file?

**Comment by cfladvad** [comment]
Simplified with two new declarations of method log(); log(String logText) and log(Throwable exc) both uses the callers class and method as tag in logmessage.

**Comment by cfladvad** [comment]
New class ErrorDialog implemented and new design for handling errors using exceptions.
