### ISSUE TITLE
SearchTab's query-builder can be better

### ISSUE THREAD

**Issue by ShadowVoid** [genomizer/genomizer-desktop#23]
It isn't as good as the manual query-builder.
I know two examples so far.
It's not possible to search for just "NOT [something]", like, "all experiments that doesn't have "s" in the ExpID".
It is possible to manually write "NOT s[ExpID]", but it's not possible to do that via the builder.
Encountered another bug, if you have one ExpID with an empty field and another with NOT ExpID "s" you end up with s[ExpID]
![Image of NOT-problem](http://a.pomf.se/zvngcu.png)

**Comment by ShadowVoid** [comment]
Oh, and the date-chooser can be improved a lot, right now it doesn't even say what format it is, is it dd/mm/yy?, dd/mm/yyyy? (rhetorical question).

**Comment by ZZZanoY** [comment]
To search for NOT s[ExpID] you have to search for ([ExpID]) NOT s[ExpID]. Even if the field is empty [ExpID] is showed in the pubmed field.
