### ISSUE TITLE
Hardcode spread throughout system.

### ISSUE THREAD

**Issue by rednatto** [genomizer/genomizer-desktop#9]
ADDITIONAL NOTE 14-06-04:
"The IP in this release is currently set to itchy.cs.umu.se:7000. This info is hardcoded into the line 111 in file 'LoginWindow.java' in folder 'gui'. "

I suspect a lot of other values are hardcoded as it is currently. Perhaps these should be consolidated to a single file for ease of maintenance.

**Comment by ShadowVoid** [comment]
constant-file exists now
